const List<Map<String, String>> currencies = [
  {"code": "USD", "name": "United States Dollar"},
  {"code": "EUR", "name": "Euro"},
  {"code": "JPY", "name": "Japanese Yen"},
  {"code": "GBP", "name": "British Pound Sterling"},
  {"code": "AUD", "name": "Australian Dollar"},
  {"code": "CAD", "name": "Canadian Dollar"},
  {"code": "CHF", "name": "Swiss Franc"},
  {"code": "CNY", "name": "Chinese Yuan"},
  {"code": "HKD", "name": "Hong Kong Dollar"},
  {"code": "NZD", "name": "New Zealand Dollar"},
  {"code": "SEK", "name": "Swedish Krona"},
  {"code": "KRW", "name": "South Korean Won"},
  {"code": "SGD", "name": "Singapore Dollar"},
  {"code": "NOK", "name": "Norwegian Krone"},
  {"code": "MXN", "name": "Mexican Peso"},
  {"code": "INR", "name": "Indian Rupee"},
  {"code": "RUB", "name": "Russian Ruble"},
  {"code": "ZAR", "name": "South African Rand"},
  {"code": "TRY", "name": "Turkish Lira"},
  {"code": "BRL", "name": "Brazilian Real"},
];
